spring:
  application:
    name: cloud-admin
server:
  port: 8503
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/
  instance:
    prefer-ip-address: true
    home-page-url-path: ${server.servlet.context-path}/swagger-ui.html
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
